language: r

branches:
  only:
    - master
r_github_packages:
    - rstudio/rmarkdown

script:
  - Rscript -e "rmarkdown::render('Rmd/git_presentation.Rmd', output_file = '../docs/index.html')"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: docs
